### PR TITLE
feat: Add new changelog page/

### PR DESCRIPTION
**Pull request by shamimbinnur**
## Description

The Changelog page is live on: https://deploy-preview-190--opensauced-landing.netlify.app/changelog

1. Initially 5 changelogs will be displayed, user has to press the `load more button` to see another 5 more changelog posts.
2. Changelogs are sorted descendingly based on the date field.
3. The changelog will be displayed initially in 120-pixel heights, to see the full content users have to click on the `see more` button.
4. The logic behind the `see more` is it will only appear if the changelog content has any image(because no image will be shown properly in 120 pixels height) or the it has more than 260 characters.

Also, this PR checks all the checkboxes in the comment below.
https://github.com/open-sauced/landing-page/pull/190#issuecomment-1916873057

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by shamimbinnur** [comment]
The work is in progress. I will write a PR description, but can you take a look at the live preview and leave feedback for now?
https://deploy-preview-190--opensauced-landing.netlify.app/changelog

@bdougie @chhristopher

**Comment by bdougie** [comment]
> The work is in progress. I will write a PR description, but can you take a look at the live preview and leave feedback for now? https://deploy-preview-190--opensauced-landing.netlify.app/changelog
> 
> @bdougie @chhristopher

Rewatch GIF Recording - 2024-01-27 at 10 59 55 AM

- The "see more" should not be there is there is not more to see. I haven't look at the code, but could count characters and only show more if it exceeds whatever the limit is. 
- The load more is not implemented, but it would nice to see that working.
- Can you remove the gradient behind the header and repeat the same header style as the blog? See below

Screen Shot 2024-01-27 at 11 07 34 AM

Are you planning to link individual pages for the updates. I'd actually prefer someone click see more and navigate a page for SEO reasons. i.e. `/changelog/more-improved-treemap-navigation`

**Comment by shamimbinnur** [comment]
@bdougie I did add the logic so that the "see more" doesn't appear if there is nothing to expand. It worked on the local machine but didn't work on live. I wanted to debug it later. So, I temporarily removed that logic.

I had no plan to make the changelog an individual post since it was inspired by the GitHub page where they did not do it like that.
No worries, I will make it a clickable individual post.

The load more button does work! There is no more post left to show. You can add it from the Sanity studio and try it out.

**Comment by bdougie** [comment]
> @bdougie I did add the logic so that the "see more" doesn't appear if there is nothing to expand. It worked on the local machine but didn't work on live. I wanted to debug it later. So, I temporarily removed that logic.

Ok. Good to know. 

> I had no plan to make the changelog an individual post since it was inspired by the GitHub page where they did not do it like that. No worries, I will make it a clickable individual post.

Example of GitHub - https://github.blog/changelog/2024-01-24-dependabot-version-updates-support-devcontainers/

> The load more button does work! There is no more post left to show. You can add it from the Sanity studio and try it out.

Sure, but I am confused by the response. I am giving you a review based on the context I have, also understanding there is no PR description. Appreciate the quick response, but without any context, it seems I am just pointing out things you are already aware of.

**Comment by bdougie** [comment]
I just created a post and have some more feedback. But apologies if this is something you are still working on. The `see more` and `collapse` are pretty close to the content and not distinguishable. 


Screen Shot 2024-01-27 at 11 33 21 AM


Screen Shot 2024-01-27 at 11 33 14 AM

It does look fine after a paragraph, just not an image.

Screen Shot 2024-01-27 at 11 33 30 AM

**Comment by bdougie** [comment]
@shamimbinnur if you are able to do the following things, we can ship this and do the rest of the things I mentioned in a future PR. I can add all changelog posts to the CMS later today.

- [ ] change the header
- [ ] Add load more logic
- [ ] Add logic for "see more"

**Comment by shamimbinnur** [comment]
@bdougie I'm sorry for the delay. Let's merge it now. I will open the next PR today.

**Comment by bdougie** [comment]
> @bdougie I'm sorry for the delay. Let's merge it now. I will open the next PR today.

Can't merge without the checkboxes mentioned above. Hopefully small fixes. Do you have the bandwidth for those?

**Comment by shamimbinnur** [comment]
@bdougie Alright. Please allow me some time. I gonna get it ready within a few hours.

**Comment by shamimbinnur** [comment]
@bdougie I hope we can merge it now. I added a description in this PR too.

**Review by bdougie — APPROVED** [review]
Going to merge this and open up some follow up issues to address the remaining things. My recommendation is approaching each issue as a separate PR so we can continue to move this to completion.

**Comment by bdougie** [comment]
@shamimbinnur all issues have been opened and placed here https://github.com/open-sauced/landing-page/milestone/1

**Pull request merged**
