### PR TITLE
[Feature] New design implementation

### PR DESCRIPTION
**Pull request by Tickerabucky2**
- Previous code refactor
- New design implementation

### CODE REVIEW

**Comment by bdougie** [comment]
build failure below. Let me know if you are not able to see it.  

```
6:32:29 AM: Error: Configuration must contain `projectId`
6:32:29 AM:     at exports.initConfig (/opt/build/repo/node_modules/@sanity/client/lib/config.js:42:11)
6:32:29 AM:     at SanityClient.config (/opt/build/repo/node_modules/@sanity/client/lib/sanityClient.js:85:25)
6:32:29 AM:     at new SanityClient (/opt/build/repo/node_modules/@sanity/client/lib/sanityClient.js:53:8)
6:32:29 AM:     at SanityClient (/opt/build/repo/node_modules/@sanity/client/lib/sanityClient.js:50:12)
6:32:29 AM:     at Object.1697 (/opt/build/repo/.next/server/chunks/308.js:1116:69)
6:32:29 AM:     at __webpack_require__ (/opt/build/repo/.next/server/webpack-runtime.js:25:42)
6:32:29 AM:     at /opt/build/repo/.next/server/pages/index.js:922:69
6:32:29 AM:     at Function.__webpack_require__.a (/opt/build/repo/.next/server/webpack-runtime.js:103:13)
6:32:29 AM:     at Object.5075 (/opt/build/repo/.next/server/pages/index.js:912:21)
6:32:29 AM:     at __webpack_require__ (/opt/build/repo/.next/server/webpack-runtime.js:25:42) {
6:32:29 AM:   type: 'Error'
6:32:29 AM: }
```

**Comment by Tickerabucky2** [comment]
> build failure below. Let me know if you are not able to see it.
> 
> ```
> 6:32:29 AM: Error: Configuration must contain `projectId`
> 6:32:29 AM:     at exports.initConfig (/opt/build/repo/node_modules/@sanity/client/lib/config.js:42:11)
> 6:32:29 AM:     at SanityClient.config (/opt/build/repo/node_modules/@sanity/client/lib/sanityClient.js:85:25)
> 6:32:29 AM:     at new SanityClient (/opt/build/repo/node_modules/@sanity/client/lib/sanityClient.js:53:8)
> 6:32:29 AM:     at SanityClient (/opt/build/repo/node_modules/@sanity/client/lib/sanityClient.js:50:12)
> 6:32:29 AM:     at Object.1697 (/opt/build/repo/.next/server/chunks/308.js:1116:69)
> 6:32:29 AM:     at __webpack_require__ (/opt/build/repo/.next/server/webpack-runtime.js:25:42)
> 6:32:29 AM:     at /opt/build/repo/.next/server/pages/index.js:922:69
> 6:32:29 AM:     at Function.__webpack_require__.a (/opt/build/repo/.next/server/webpack-runtime.js:103:13)
> 6:32:29 AM:     at Object.5075 (/opt/build/repo/.next/server/pages/index.js:912:21)
> 6:32:29 AM:     at __webpack_require__ (/opt/build/repo/.next/server/webpack-runtime.js:25:42) {
> 6:32:29 AM:   type: 'Error'
> 6:32:29 AM: }
> ```

I thought that would be smart to remove sanity sensitive data (projectId and token) from the code and move it to the .env. I haven't included it in my PR since the repo is public and there is no difference if it is in the .env file or inside the code. Of course, It is Your call on how to proceed with this thing I have just followed the standard practice.

**Comment by bdougie** [comment]
> Your call on how to proceed with this thing I have just followed the standard practice.

I added them as env variables to Netlify. You will need to do a new push to trigger a new deploy preview build.

**Comment by bdougie** [comment]
Curious about what state this is in. Noticing that the placeholder icons are used instead of the designed assets. 
Screen Shot 2022-11-30 at 10 27 39 AM

**Pull request merged**
