### PR TITLE
feat: Press to link

### PR DESCRIPTION
**Pull request by shamimbinnur**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR is related to issue #33.
In this PR a link to press is been created, where there will be OpenSauced logos for third-party usage.
We will be able to add, delete, and edit the press page's content through the sanity admin panel.

Link to access the page:  https://opensauced.pizza/press
Deploy preview link: https://deploy-preview-41--opensauced-landing.netlify.app/press

## Related Tickets & Documents

fixes issue #33 

## Mobile & Desktop Screenshots/Recordings
Screenshot 2022-09-11 at 7 53 42 PM
Screenshot 2022-09-11 at 7 53 31 PM

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by shamimbinnur** [comment]
#33

**Comment by shamimbinnur** [comment]
@bdougie This PR should be merged before #42

**Comment by bdougie** [comment]
Thanks for jumping on this. I failed to provide the actual presskit images. Can you use the attached PNGs

[Open Sauced Press Kit.zip](https://github.com/open-sauced/landing-page/files/9552399/Open.Sauced.Press.Kit.zip)

**Comment by bdougie** [comment]
Full-Wordlogo-White
Full-Wordlogo
Slice-Logo
Wordlogo

**Comment by shamimbinnur** [comment]
@bdougie attached the logos and fixed some responsiveness issues. Can please take a look again?

**Review by bdougie — APPROVED** [review]
Thanks this looks good. I will add copy when this is merged.

**Pull request merged**
