### PR TITLE
Add static fonts & remove fonts link from SEO.tsx

### LINKED ISSUE #177: Bug: Font and stylesheet should be add _document.
### Describe the bug

Getting warning in development on browser's console "Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700&family=Open+Sans:wght@300;400;500;600;700;800&display=swap"). Use Document instead." 
This link tag is used in SEO component.

### Steps to reproduce

1. Run `npm run dev`
2. Open the home page in a browser
3. Check warnings in console

### Browsers

_No response_

### Additional context (Is this in dev or production?)

Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by Sunny-unik**
## Description

Fonts link in the SEO component gives a warning that is also mentioned in an issue. This PR resolves issue #177. 
In this PR:
- Added Inter and OpenSans fonts (both of these fonts are present in the previous fonts link)
- Remove fonts link from the SEO component

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Fixes #177

## Mobile & Desktop Screenshots/Recordings

Before: 
Screenshot 2023-11-16 184717

After:
Screenshot 2023-11-16 192943

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
Thanks for the cleanup @Sunny-unik! 🚢

**Review by OgDev-01 — APPROVED** [review]

**Comment by dev-phantom** [comment]
I guess this pr fixed the issue #177 

please why was it closed?
@OgDev-01, @bdougie

**Comment by bdougie** [comment]
> I guess this pr fixed the issue #177
> 
> please why was it closed? @OgDev-01, @bdougie

I honestly don't know why. My thought is that it would conflict with some other changes we had planned. But I did not leave a note on that. So I guess I closed this in error.

**Comment by bdougie** [comment]
Ah I see, you have a similar PR open as well https://github.com/open-sauced/landing-page/pull/203

**Review by bdougie — APPROVED** [review]

**Pull request merged**
