### PR TITLE
fix: replace saucy blog with featured

### PR DESCRIPTION
**Pull request by shamimbinnur**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR will replace the "Saucy Blog section with "Featured"

## Related Tickets & Documents
fixes: #40 

## Mobile & Desktop Screenshots/Recordings

Screenshot 2022-09-11 at 8 47 00 PM

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by shamimbinnur** [comment]
@bdougie this PR should be merged right after when #41 is merged. I will take over to resolve the merge conflict then.

**Comment by bdougie** [comment]
#41 has been merged. please assist with the merge conflict.

**Comment by shamimbinnur** [comment]
> #41 has been merged. please assist with the merge conflict.

Sure! Just give me some times

**Comment by shamimbinnur** [comment]
@bdougie Conflict with main has been resolved, you can merge!

**Pull request merged**
