### PR TITLE
fix: make "we are more than... green squares" slogan accessible

### LINKED ISSUE #88: Feature: Green squares is not accesible
### Type of feature

🍕 Feature

### Current behavior

reported [here](https://twitter.com/mislav/status/1603062302420668416). 

> The “We are more than green squares” graphic is visually cool, but is marked up by 4 distinct block elements. A screen reader would likely read that as 4 paragraphs. The graphic could be marked up by a single <p> containing spans to chop it up visually via CSS.

Screen Shot 2022-12-14 at 9 35 50 AM

### Suggested solution

This image should convert to a custom CSS.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by CBID2**
## Description
This PR is a new of #164 
> [!NOTE]
> Read [the description section in pull request #164](https://github.com/open-sauced/landing-page/pull/164) for more context.

## Related Tickets & Documents
Closes #88

https://github.com/open-sauced/landing-page/assets/105683440/c56fd2ba-e537-41a9-8e28-1cf9c9efb1f9

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

### CODE REVIEW

**Comment by CBID2** [comment]
Hey @nickytonline or @bdougie, can this PR be merged?

**Comment by nickytonline** [comment]
> Hey @nickytonline or @bdougie, can this PR be merged?

I'm not really understanding the title of this PR and how this addresses the accessibility issue reported.

I also can't find the page this is located on in the site. I don't think it's in the production site anymore, at least from navigating around. What page(s) can I go to to test this?

**Comment by nickytonline** [comment]
> Hi @nickytonline. @bdougie encouraged me to do a new version of PR #164. It was sitting around for quite some time. This is why the square is no longer present.

Which page(s) in the deploy preview can I test this on? I can't seem to find it and there's no QA instructions.

**Comment by CBID2** [comment]
> > Hi @nickytonline. @bdougie encouraged me to do a new version of PR #164. It was sitting around for quite some time. This is why the square is no longer present.
> 
> 
> 
> Which page(s) in the deploy preview can I test this on? I can't seem to find it and there's no QA instructions.

It used to be on the teams page in the website, but I think it went away.

**Comment by nickytonline** [comment]
As it doesn't seem to be used anywhere now, I'm going to go ahead and close this.

**Pull request closed without merging**
