### PR TITLE
feat: upgrade Sanity Studio to v3

### LINKED ISSUE #328: Bug: Move off of abandoned `sanity-codegen`
The Sanity Codegen project has been archived: https://github.com/ricokahler/sanity-codegen

> As the sole maintainer of sanity-codegen, I found myself unable to dedicate the time and attention it truly deserved. That's why I'm thrilled to announce the arrival of Sanity TypeGen! This project is a complete replacement for sanity-codegen and is maintained in-house by the same team that maintains GROQ itselt

It'd also be good to move off of this since there are existing Dependabot security alerts related to transient dependencies carried in `sanity-codegen` (likely since it hasn't been updated in some time).

---

I took a brief look at using the new Sanity TypeGen and it won't be trivial unfortunately: we're still on an old version of Sanity studio:

https://github.com/open-sauced/landing-page/blob/6768fb928b97c89622787085b7d94a12d02bad66/sanity/package.json#L17

which was deprecated this last December:

- https://github.com/open-sauced/landing-page/issues/185

---

TLDR:

- [ ] Upgrade to Sanity v3
- [ ] Remove `sanity-codegen`
- [ ] Utilize Sanity TypeGen

### LINKED ISSUE #333: Bug: Move off abandoned `sanity-plugin-asset-source-ogimage` package
### Describe the bug

This package was archived on 07/17/24 and is no longer maintained

https://github.com/hdoro/sanity-plugin-asset-source-ogimage#readme

We should find a replacement 

### Steps to reproduce

N/A

### LINKED ISSUE #335: Bug: Sanity Studio not working
### Describe the bug

It appears that in the upgrade of Sanity Studio (via #334), I broke Sanity Studio. Currently, if you follow the instructions in the Readme, you get this error:

image
 

### Steps to reproduce

1. Install [Sanity Studio](https://www.sanity.io/docs/getting-started-with-sanity-cli):

- npm install -g @sanity/cli
- Start the local [Sanity Studio](https://www.sanity.io/docs/getting-started-with-sanity-cli) which will be available at http://localhost:3333/:

- cd sanity
- npm install # only needs to be ran once
- sanity start
- See error

### PR DESCRIPTION
**Pull request by brandonroberts**
## Description

- Upgrades Sanity Studio to v3
- Regenerated Sanity types
- Updated references to newly generated typs
- Updated Sanity Studio dependencies

## Related Tickets & Documents

Closes #328 
Closes #333 
Closes #335

## Steps to QA

1. checkout PR
2. cd sanity
3. Run `npm install`
4. Run `npm start`
5. Navigate to `http://localhost:3333` to view studio

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Review by nickytonline — COMMENTED** [review]
There's a build error

```
4:20:03 PM: Failed to compile.
4:20:03 PM: 
4:20:03 PM: ./components/common/layout/PageLayout.tsx:2:45
4:20:03 PM: Type error: Cannot find module '../../../types/schema' or its corresponding type declarations.
4:20:03 PM:   1 | import React, { FC, ReactElement } from 'react'
4:20:03 PM: > 2 | import { SanityNavigation, SanitySeo } from '../../../types/schema'
```

**Review by nickytonline — APPROVED** [review]
:shipit:

**Comment by BekahHW** [comment]
@brandonroberts it appears that [Sanity Studio broke](https://github.com/open-sauced/landing-page/issues/335) in one of my previous PRs. Idk if we want to address that here? I'm not able to run Sanity Studio on your branch either.

**Comment by nickytonline** [comment]
> @brandonroberts it appears that [Sanity Studio broke](https://github.com/open-sauced/landing-page/issues/335) in one of my previous PRs. Idk if we want to address that here? I'm not able to run Sanity Studio on your branch either.

Consider fixing that in a separate PR @BekahHW as it's not related to the upgrade.

**Comment by BekahHW** [comment]
@nickytonline I think it is related to the upgrade, but not caused by this PR. That's why I mentioned it here.

**Comment by brandonroberts** [comment]
@BekahHW I ran into that also. If you run `npm install` at the root, then go into the `sanity` directory and run `npm install`, then `npm start` it works correctly. Not sure why that's needed as `sanity` is a dependency in both `package.json` files.

**Review by BekahHW — APPROVED** [review]

**Pull request merged**
