### PR TITLE
fix: update twitter icon to X

### LINKED ISSUE #168: Bug: Request to update twitter icon to X
### Describe the bug

The Twitter icon at the footer section or bottom of the page should be updated to the X icon.

image

### Steps to reproduce

1. Go to 'https://opensauced.pizza/'
2. Scroll to the footer or bottom of the page.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by RitaDee**
## Description
Update the Twitter logo to a simplified version with a new SVG code. 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #168

## Mobile & Desktop Screenshots/Recordings

Before:
image

After:
Screenshot 2023-09-29 at 14 59 16

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
Thanks @RitaDee! :shipit:

**Comment by RitaDee** [comment]
image

I tried changing the Twitter icon to the X icon on the "About" page, but I suspect it is from the CMS (Sanity Studio). Am I right?

**Comment by takanome-dev** [comment]
> I tried changing the Twitter icon to the X icon on the "About" page, but I suspect it is from the CMS (Sanity Studio). Am I right?

cc @RitaDee, I think it's here
https://github.com/open-sauced/landing-page/blob/457c4ac4f31da7bf44a91b38c414c0e6e7197be5/components/common/SocialLinks.tsx#L15-L17

**Comment by bdougie** [comment]
We can do it directly in the cams after this is merged.

**Comment by RitaDee** [comment]
> cms

Okay

**Comment by RitaDee** [comment]
> We can do it directly in the cms after this is merged.

Great!

**Review by OgDev-01 — APPROVED** [review]
LGTM 🍕

**Comment by OgDev-01** [comment]
> > I tried changing the Twitter icon to the X icon on the "About" page, but I suspect it is from the CMS (Sanity Studio). Am I right?
> 
> cc @RitaDee, I think it's here
> 
> https://github.com/open-sauced/landing-page/blob/457c4ac4f31da7bf44a91b38c414c0e6e7197be5/components/common/SocialLinks.tsx#L15-L17

update this and we are good @RitaDee  🤗

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
