### PR TITLE
feat: add missing canonical tags

### LINKED ISSUE #313: Add Missing Canonical Tags
Self-referential rel=canonical tags are missing on 23 of your pages.
Self-referential canonical tags are a preventive measure to guarantee Google indexes the primary version of each page on your website.

## Solution

- [ ] Add a self-referencing rel=canonical tag to every page unless there's another primary version of that content. (unlabeled fall into this category)
- [ ] For secondary-version pages, add a rel=canonical that points to the primary version. 
- [ ] https://opensauced.pizza/blog/growth-hacking-killed-github-stars
- [ ] https://opensauced.pizza/blog/scaling-oss-projects
- [ ] https://opensauced.pizza/blog/ai-secret-sauce-traction-in-open-source
- [ ] https://opensauced.pizza/changelog
- [ ] https://opensauced.pizza/blog
- [ ] https://opensauced.pizza/about
- [ ] https://opensauced.pizza/press
- [ ] https://opensauced.pizza/blog/measuring-success-in-open-source
- [ ] https://opensauced.pizza/blog/you-don’t-need-a-mentor
- [ ] https://opensauced.pizza/blog/stop-burning-out-maintainers:-an-empathetic-guide-for-contributors
- [ ] https://opensauced.pizza/blog/our-hacktoberfest-success-story
- [ ] https://opensauced.pizza/blog/moneyball-for-engineers
- [ ] https://opensauced.pizza/blog/1000-developers-choose-open-source
- [ ] https://opensauced.pizza/changelog/opensauced-api-2.0
- [ ] https://opensauced.pizza/changelog/more-reliable-user-contributions-data
- [ ] https://opensauced.pizza/blog/bridging-the-gap-organizational-insights?ref=news.opensauced.pizza (Missing Canonical)
- [ ] https://opensauced.pizza/blog/the-lonely-journey-of-open-source-maintainers?ref=news.opensauced.pizza(Missing Canonical)
- [ ] https://opensauced.pizza/changelog?ref=news.opensauced.pizza (Missing Canonical)
- [ ] https://opensauced.pizza/changelog/see-contributor-highlights-right-from-your-contributor-insights-page
- [ ] https://opensauced.pizza/blog/stop-burning-out-maintainers-an-empathetic-guide-for-contributors
- [ ] https://opensauced.pizza/?ref=news.opensauced.pizza (Missing Canonical)
- [ ] https://opensauced.pizza/blog/good-first-issues-dont-exist?ref=news.opensauced.pizza (Missing Canonical)

**Note**: A couple of these are for the newsletter, so that might need to be delayed until looking into ghost

### PR DESCRIPTION
**Pull request by CBID2**
## Description
This PR adds a canonical tag for the blogs, improving its SEO. 

## Related Tickets & Documents
Closes #313 

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

Lets hope this works GIF

### CODE REVIEW

**Comment by CBID2** [comment]
Hey @BekahHW! :) I made a draft PR for this issue. I hope it is what you had in mind.

**Comment by BekahHW** [comment]
@CBID2 we'll be merging in a PR before this that upgrades sanity studio, so let's wait until that gets merged in. You'll need to check each of the pages on the checklist to make sure they have the correct canonical_url. It looks like the blog posts are getting picked up, but there are other pages on the list. We can potentially break it into two issues though.

**Comment by CBID2** [comment]
> @CBID2 we'll be merging in a PR before this that upgrades sanity studio, so let's wait until that gets merged in. You'll need to check each of the pages on the checklist to make sure they have the correct canonical_url. It looks like the blog posts are getting picked up, but there are other pages on the list. We can potentially break it into two issues though.
> 
> 

Good idea @BekahHW. I think for the second part of this issue, having some sort of example on how to add the canonical link would help.

**Comment by BekahHW** [comment]
> Good idea @BekahHW. I think for the second part of this issue, having some sort of example on how to add the canonical link would help.

If it were a good-first-issue, I would have an example. Taking a look at the codebase and checking documentation should lead you on the right path.

**Comment by BekahHW** [comment]
@CBID2 can you merge in the latest changes and give me an update on how the issues going when you get a chance?

**Comment by CBID2** [comment]
> @CBID2 can you merge in the latest changes and give me an update on how the issues going when you get a chance?

Hey @BekahHW. I just updated my branch with the latest changes. I'm currently working on my PR via Gitpod(I tried doing it locally but my computer runs slow when I do) and I get this message whenever I click on [the Editing SEO Content link in the Readme](https://github.com/open-sauced/landing-page/blob/main/README.md#-editing-seo-content)
Screenshot of error. 
According to Gitpod's Docs, it is recommended to [Configure the port](https://www.gitpod.io/docs/configure/workspaces/ports#configure-port-opening), but I'm a bit hesitant to do that as I don't want to mess up the main repo. What do you recommend?

**Comment by BekahHW** [comment]
I haven't used gitpod before. What other resources did you look at to navigate the issues you're having?

**Comment by BekahHW** [comment]
@CBID2 do you have an update here? I'd like to get the issue completed soon.

**Comment by CBID2** [comment]
> @CBID2 do you have an update here? I'd like to get the issue completed soon.

Hey @BekahHW. I haven't been feeling well for a couple of days so I didn't get a chance to find another alternative.

**Comment by CBID2** [comment]
> @CBID2 do you have an update here? I'd like to get the issue completed soon.

Seems like this method with Gitpod is the only one I can do: https://www.gitpod.io/docs/configure/workspaces/ports

**Comment by CBID2** [comment]
Hey @BekahHW. I decided to close this PR. You can work on this issue

**Pull request closed without merging**
