### PR TITLE
feat: pin changelog when scrolling

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

When scrolling through `/changelog`, the title will become sticky until the entire changelog scrolls by.

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Addresses #191 

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/landing-page/assets/20603494/253e5709-1dc8-4fff-8a23-3c203ae15a00

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

sticky af

### CODE REVIEW

**Review by nickytonline — COMMENTED** [review]
I tried the deploy preview and pulled it down locally, but it doesn't seem to stick as you scroll the changelog, in Chrome. I see it working in the video though. Maybe a commit wasn't pushed?

**Comment by zeucapua** [comment]
> I tried the deploy preview and pulled it down locally, but it doesn't seem to stick as you scroll the changelog, in Chrome. I see it working in the video though. Maybe a commit wasn't pushed?


https://github.com/open-sauced/landing-page/assets/20603494/26034a9b-6e0f-4b4a-9d7d-416ed92e987a

Opening it up via the preview deploy works for me. It doesn't sticky if the content isn't expanded on the right since there isn't enough height to scroll through, but otherwise looks fine. Mind sending a video on how it looks for you?

**Comment by nickytonline** [comment]
I see it working now. I had the sections collapsed which is why it wasn't kicking in.

**Review by nickytonline — APPROVED** [review]
Thanks @zeucapua! Works great! 🚢

**Review by bdougie — APPROVED** [review]
LGTM. Thanks @zeucapua!

**Pull request merged**
