### PR TITLE
Sanity work

### PR DESCRIPTION
**Pull request by shamimbinnur**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by bdougie — APPROVED** [review]

**Comment by bdougie** [comment]
Blog posts are completely empty.

Screen Shot 2023-01-28 at 12 54 34 PM

**Comment by bdougie** [comment]
oh, probably because this needs to be merge

**Comment by shamimbinnur** [comment]
> https://deploy-preview-98--opensauced-landing.netlify.app

@bdougie  Yep!
Check out here: https://deploy-preview-98--opensauced-landing.netlify.app/blog/good-first-issues-dont-exist

**Comment by bdougie** [comment]
Ok. When the merge conflicts are resolved, please go ahead and hit merge.

**Pull request merged**
