### PR TITLE
Handle reported release issues

### PR DESCRIPTION
**Pull request by Tickerabucky2**
Each resolved issue can be identified based on the commit name.

### CODE REVIEW

**Review by bdougie — APPROVED** [review]
Just need to rebase main to capture the copy changes made yesterday https://github.com/open-sauced/landing-page/pull/84

**Comment by Tickerabucky2** [comment]
> Just need to rebase main to capture the copy changes made yesterday #84

Please check this [LINK](https://github.com/open-sauced/landing-page/pull/85/files#diff-fe81383e3f7af41b52e518ddb477b9427ad8075aa4187319a457574584fb7be6), line 21. Changes are there but not reflected in the deployed PR version. Could be some pipeline cache issue.

**Comment by Tickerabucky2** [comment]
> Just need to rebase the main to capture the copy changes made yesterday #84

Did the rebase but now conflicts are back and no changes are reflected nether. I will pull the main branch again and resolve the conflicts.

**Comment by Tickerabucky2** [comment]
@bdougie Changes are now visible.

**Pull request merged**
