### PR TITLE
feat: Social card

### LINKED ISSUE #94: Feature: Open Image social cards
### Type of feature

🍕 Feature

### Current behavior

When sharing a blog post from the landing page, we should provide an open graph image. 

### Suggested solution

https://www.sanity.io/plugins/asset-source-ogimage

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by shamimbinnur**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
1. Adds the ability to generate Open Graph images for every blog from sanity studio.
2. The website has been modified to fetch Open Graph images on the blog page.

## Related Tickets & Documents
Fixes #94 

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
Is it possible to limit the length of the card to the red line

Screen Shot 2023-02-04 at 9 15 18 AM

**Comment by shamimbinnur** [comment]
> Is it possible to limit the length of the card to the red line
> 
> Screen Shot 2023-02-04 at 9 15 18 AM
> 
> 

@bdougie Yes, it is! Can provide me with a measurement for this?

**Comment by bdougie** [comment]
70% max width. I don't have specific measurements.

**Comment by shamimbinnur** [comment]
> 70% max width. I don't have specific measurements.

Alright , no problem.

**Comment by shamimbinnur** [comment]
Screenshot 2023-02-05 at 11 07 18 PM

Screenshot 2023-02-05 at 11 06 55 PM

**Comment by bdougie** [comment]
@shamimbinnur would be able to create a highlight about your work on this fix?

https://opensauced.pizza/blog/social-coding-is-back

**Comment by shamimbinnur** [comment]
@bdougie Yes! I would love to do that!

**Pull request merged**
