### PR TITLE
fix: blog featured post

### PR DESCRIPTION
**Pull request by nickytonline**
## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Review by brandonroberts — DISMISSED** [review]

**Review by jpmcb — CHANGES_REQUESTED** [review]
@nickytonline - you need to rebase this since it looks like you're carrying commits over from https://github.com/open-sauced/landing-page/pull/358

**Comment by nickytonline** [comment]
> @nickytonline - you need to rebase this since it looks like you're carrying commits over from #358

Yeah,  I accidentally used an old branch. 🙈 Just rebasing.

**Comment by nickytonline** [comment]
I think the GitHub UI is not reflecting my latest. Did another push force, but it still shows multiple commits here. 😅 

CleanShot 2024-09-16 at 13 12 08

**Comment by jpmcb** [comment]
The tip of your `fix-blog-featured-post` has 4 commits (including those from `godsfavour1975@gmail.com`:

Screenshot 2024-09-16 at 11 18 57 AM

It looks like you picked these up from your branch being based on: https://github.com/open-sauced/landing-page/pull/357 which is also getting your force pushes and has your pizza-action commit. So you probably started from a dirty state.

You could drop those commits in an interactive rebase:

```
d eb65f477 fix: fixed featured post img
d 00d046da Update components/sections/blog/components/Post.tsx
d e26af92c Update components/sections/blog/FeaturedPost.tsx
pick 75638c22 chore: updated pizza action
```

but it'd probably just be easier to throw out this branch, pull down from `main` and ensure you don't have other commits

**Comment by nickytonline** [comment]
Ahh, I see what I did. I'm on @dev-phantom's PR by accident. Sorry about that @dev-phantom! Going to remove my last commit.

**Comment by nickytonline** [comment]
Looks like I can't remove my last commit @dev-phantom. If you can force push what you have on your local that should get you back to where you were at. Again, apologies. 😅

**Pull request closed without merging**
