### PR TITLE
UI refresh

### PR DESCRIPTION
**Pull request by shamimbinnur**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
New Design for the landing page.

## Mobile & Desktop Screenshots/Recordings
Screenshot 2022-10-27 at 7 30 11 PM
Screenshot 2022-10-27 at 7 30 25 PM

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
Looks like the image is there twice. 
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1280 x 559 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-70--opensauced-landing.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1280x559&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-70--opensauced-landing.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=635a8a37cab6a4000969aac5&commentID=635c4fc8a6608253aa144ed2&resolution=resolved)

**Comment by bdougie** [comment]
screenshot

Local data is not the same. 

<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1280 x 559 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-70--opensauced-landing.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1280x559&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-70--opensauced-landing.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=635a8a37cab6a4000969aac5&commentID=635c4ff0a8597355b116c250&resolution=resolved)

**Comment by bdougie** [comment]
screenshot

this image is not high-res

<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1280 x 559 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-70--opensauced-landing.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1280x559&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-70--opensauced-landing.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=635a8a37cab6a4000969aac5&commentID=635c5019a158b8486880a147&resolution=resolved)

**Review by bdougie — CHANGES_REQUESTED** [review]
Can we get @pixelsbyeryc to update the name in the image to something other than "JessicaAward" too. Thanks

**Comment by shamimbinnur** [comment]
> Looks like the image is there twice. screenshot
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-70--opensauced-landing.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=635a8a37cab6a4000969aac5&commentID=635c4fc8a6608253aa144ed2&resolution=resolved)

@bdougie  It just turned into an undwanted transparent image after exporting this in SVG. I will replace this image when eryc provide the correct image.

**Comment by shamimbinnur** [comment]
> screenshot
> 
> Local data is not the same.
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-70--opensauced-landing.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=635a8a37cab6a4000969aac5&commentID=635c4ff0a8597355b116c250&resolution=resolved)

@bdougie  These all are the new icons. So initially I kept as static file rather than fetching from CMS. Because that would effect our main landing page. We can make it dynamic once our new version of the site is launced.

**Comment by bdougie** [comment]
We should be using the logos from the live pages. If we need them updated in the design, let Christian know. Otherwise a version can be found on the represented companies press page.

**Comment by shamimbinnur** [comment]
> https://deploy-preview-70--opensauced-landing.netlify.app

@bdougie Updated this!

**Comment by shamimbinnur** [comment]
> Looks like the image is there twice. screenshot
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-70--opensauced-landing.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=635a8a37cab6a4000969aac5&commentID=635c4fc8a6608253aa144ed2&resolution=resolved)

@bdougie The image has been updated now.

**Review by bdougie — APPROVED** [review]
Merging this as-is @shamimbinnur. In preparation for the keynote. Please create a new branch for future work. 

- Features
- Blog
- Tweets
- newsletter

**Pull request merged**
